name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - uses: actions/checkout@v4

            - uses: pdm-project/setup-pdm@v4
              name: Setup PDM
              with:
                  python-version: '3.9'
                  architecture: 'x64'
                  cache: true

            - run: pdm sync -G:all
              shell: bash

            - name: Get Version
              id: version
              run: |
                  echo "VERSION=$(pdm show --version)" >> $GITHUB_OUTPUT
                  echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
                  echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Check Version
              if: steps.version.outputs.VERSION != steps.version.outputs.TAG_VERSION
              run: exit 1

            - name: Publish Package
              run: |
                  pdm publish
                  gh release create ${{ steps.version.outputs.TAG_NAME }} dist/*.tar.gz dist/*.whl -t "🔖 ${{ steps.version.outputs.TAG_NAME }}" --generate-notes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
